### ISSUE TITLE
Add this to python?

### ISSUE THREAD

**Issue by melonmouse** [Rockhopper-Technologies/prefixed#6]
Formatting output as SI and IEC is super important and common! Just letting you know I'm a fan of `prefixed`. I think many people don't realize they need it, or can't find `prefixed` and end up rolling their own.

Now, I don't want to add work to the Rockhopper-Technologies plate, but...

...how cool would it be to have this be part of python?

You are the experts on this! Looking at the history of string, there are new formats every now and then:
https://docs.python.org/3/library/string.html#formatspec

Following the most recent example (the `z` literal), AFAIK the process is to [write a PEP](https://peps.python.org/pep-0682/) and then [implement](https://github.com/python/cpython/pull/30049/commits) it. That is probably a lot of work, but not impossible either.

**Comment by melonmouse** [comment]
Found documentation on [how propose python language changes](https://devguide.python.org/developer-workflow/lang-changes/#langchanges).

They say the first step is to [post the idea on the discussion board](https://discuss.python.org/c/ideas/6). I'm under the impression that your idea [has not](https://discuss.python.org/search?q=prefix%20%23ideas) [been posted](https://discuss.python.org/search?q=format%20%23ideas) there before.

**Comment by avylove** [comment]
I posted [here](https://discuss.python.org/t/new-format-specifiers-for-string-formatting-of-floats-with-si-and-iec-prefixes/26914) to see what the appetite might be for a PEP. @melonmouse, it might be good to voice your support there.

**Comment by melonmouse** [comment]
Taking a look there now

**Comment by avylove** [comment]
Going to close this. I hope those discussions go somewhere. Thanks for your support!
