### ISSUE TITLE
µ symbol

### ISSUE THREAD

**Issue by automesslar** [Rockhopper-Technologies/prefixed#8]
There are two similar looking symbols „µ“ (U+00B5) and „μ“ (U+03BC). This lib only works with the second one. But to my knowlege the first one ist usually used for micro (10^-6) and the second one is from the greek alphabet.

This is a problem when doing something like:
`Float('100.0µ')`
which results in:
`ValueError: Could not convert str to Float: '100.0µ'`

**Comment by avylove** [comment]
Thanks for reporting!
According to [Unicode Technical Report #25](https://www.unicode.org/reports/tr25) section 2.5, U+03BC is preffered and U+00B5 is considered legacy. But you are correct that they should both be supported. I just released [version 0.9.0](https://github.com/Rockhopper-Technologies/prefixed/releases/tag/0.9.0), this should solve your issue.

**Comment by automesslar** [comment]
I didn't know about the Unicode recommendations, but version 0.9.0 works perfectly. Thank you :)
